apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-stg

resources:
- ./../../base

patchesStrategicMerge:
  - argo-cd.yaml
  - argo-wrokflows.yaml
  - kustomization.yaml
ar