apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd
    repoURL: https://github.com/r-kohsei-ishihara/argo-cd-manifest.git
    targetRevision: main
  syncPolicy:
    automated: {}